# Generated for Admin model with custom teaching algorithm fields

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Unique admin username",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "salt",
                    models.CharField(
                        help_text="64-character random hexadecimal salt generated using secrets.token_hex(32)",
                        max_length=64,
                    ),
                ),
                (
                    "password_hash",
                    models.CharField(
                        help_text="64-character hash generated by our custom teaching algorithm",
                        max_length=64,
                    ),
                ),
            ],
        ),
    ]
