# student/models.py
#
# WHAT: Defines the MySQL database schema for Student accounts.
#
# WHY:  Django models map Python classes to database tables.
#       This model stores basic student information, credentials (hashed password + salt),
#       academic department, year of study, and account creation timestamp.
#
# COLLEGE REQUIREMENT:
#       We do NOT use Django's auth User model.
#       This is our own custom, lightweight Student table.

from django.db import models


class Student(models.Model):
    """
    Represents a Student account in MySQL.
    Table name: student_student
    """

    # id: Integer Auto-increment primary key (automatically created by Django)

    # name: Student's full name
    name = models.CharField(
        max_length=150,
        help_text="Full name of the student"
    )

    # email: Unique student email used as login identifier
    email = models.EmailField(
        max_length=255,
        unique=True,
        help_text="Unique student email address"
    )

    # password_hash: 64-character hexadecimal hash generated by our custom teaching algorithm
    password_hash = models.CharField(
        max_length=64,
        help_text="64-character hash produced by custom teaching algorithm"
    )

    # salt: 64-character random hexadecimal salt generated using secrets.token_hex(32)
    salt = models.CharField(
        max_length=64,
        help_text="64-character random hexadecimal salt"
    )

    # department: Academic department (e.g. Computer Engineering, IT)
    department = models.CharField(
        max_length=100,
        blank=True,
        default="",
        help_text="Academic department / branch"
    )

    # year: Academic year of study (e.g. First Year, Second Year, Third Year, Final Year)
    year = models.CharField(
        max_length=50,
        blank=True,
        default="",
        help_text="Current academic year"
    )

    # created_at: Automatically records timestamp when student registers
    created_at = models.DateTimeField(
        auto_now_add=True,
        help_text="Timestamp of account creation"
    )

    def __str__(self):
        return f"{self.name} ({self.email})"
