# Generated by Django 6.1.1 on 2026-09-27 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the assignment or exam (e.g. Data Structures Assessment 1)",
                        max_length=200,
                    ),
                ),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("FINAL", "Final Exam"),
                            ("SUBJECT", "Subject-wise Exam"),
                        ],
                        default="SUBJECT",
                        help_text="Category: Final Exam or Subject-wise Exam",
                        max_length=20,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Subject name (e.g. Operating Systems, Data Structures, Aptitude)",
                        max_length=100,
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Specific topic (e.g. Paging, Arrays, Probability)",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Instructions or description for students before starting",
                    ),
                ),
                (
                    "time_limit",
                    models.PositiveIntegerField(
                        default=30, help_text="Duration in minutes"
                    ),
                ),
                (
                    "total_marks",
                    models.PositiveIntegerField(
                        default=0, help_text="Total marks available for this exam"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("CLOSED", "Closed"),
                        ],
                        default="DRAFT",
                        help_text="Draft (admin only), Published (students can attempt), Closed (archived)",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when assignment was created",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When student clicked Start Test"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When student submitted (or auto-submitted by timer)",
                        null=True,
                    ),
                ),
                (
                    "score",
                    models.PositiveIntegerField(
                        default=0, help_text="Total marks obtained by the student"
                    ),
                ),
                (
                    "percentage",
                    models.FloatField(
                        default=0.0,
                        help_text="Percentage scored (score / total_marks * 100)",
                    ),
                ),
                (
                    "correct_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of fully correct questions"
                    ),
                ),
                (
                    "wrong_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of incorrect questions"
                    ),
                ),
                (
                    "unattempted_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of questions student left blank"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="IN_PROGRESS",
                        help_text="In Progress while timer runs; Completed once submitted",
                        max_length=20,
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        help_text="Assignment being attempted",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="assignments.assignment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Student who took the test",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="student.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "unique_together": {("student", "assignment")},
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_text",
                    models.TextField(help_text="The question problem statement"),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("MCQ", "Single Choice (MCQ)"),
                            ("MSQ", "Multiple Select (MSQ)"),
                        ],
                        default="MCQ",
                        help_text="MCQ (single correct) or MSQ (one or more correct)",
                        max_length=10,
                    ),
                ),
                (
                    "marks",
                    models.PositiveIntegerField(
                        default=1, help_text="Marks awarded if answered correctly"
                    ),
                ),
                (
                    "solution",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Explanation or step-by-step solution shown after submission",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=1, help_text="Display order in test"
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        help_text="The assignment this question belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="assignments.assignment",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="QuestionOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "option_label",
                    models.CharField(help_text="A, B, C, D, etc.", max_length=5),
                ),
                (
                    "option_text",
                    models.CharField(
                        help_text="Content text of this option", max_length=500
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        default=False,
                        help_text="True if this option is part of the correct answer",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        help_text="Question this option belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="assignments.question",
                    ),
                ),
            ],
            options={
                "ordering": ["option_label", "id"],
            },
        ),
        migrations.CreateModel(
            name="StudentAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        default=False,
                        help_text="True if student scored full marks on this question",
                    ),
                ),
                (
                    "marks_obtained",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Marks awarded for this question (full marks or 0)",
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        help_text="Parent attempt record",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="assignments.attempt",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        help_text="Question answered",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_answers",
                        to="assignments.question",
                    ),
                ),
            ],
            options={
                "unique_together": {("attempt", "question")},
            },
        ),
        migrations.CreateModel(
            name="SelectedOptionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        help_text="Option chosen by the student",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assignments.questionoption",
                    ),
                ),
                (
                    "student_answer",
                    models.ForeignKey(
                        help_text="Parent student answer",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selected_records",
                        to="assignments.studentanswer",
                    ),
                ),
            ],
        ),
    ]
