# Generated by Django 6.1.1 on 2026-09-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the student", max_length=150
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Unique student email address",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "password_hash",
                    models.CharField(
                        help_text="64-character hash produced by custom teaching algorithm",
                        max_length=64,
                    ),
                ),
                (
                    "salt",
                    models.CharField(
                        help_text="64-character random hexadecimal salt", max_length=64
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Academic department / branch",
                        max_length=100,
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Current academic year",
                        max_length=50,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp of account creation"
                    ),
                ),
            ],
        ),
    ]
