# Generated by Django 6.1.1 on 2026-09-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="certifications",
            field=models.TextField(
                blank=True, default="", help_text="Courses or certifications completed"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="cgpa",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Cumulative Grade Point Average (out of 10.00)",
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="github_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="GitHub or LeetCode/HackerRank profile URL",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="linkedin_url",
            field=models.URLField(
                blank=True, default="", help_text="LinkedIn profile URL", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="prn",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Permanent Registration Number / College Roll Number",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="projects",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Key academic or personal projects summary",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="resume_link",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Link to online resume or portfolio",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="skills",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Technical skills (e.g., Python, Django, MySQL, Data Structures)",
            ),
        ),
    ]
