# adminpanel/models.py
#
# WHAT: Defines the MySQL database schema for the Admin account.
#
# WHY:  Django models map Python classes to database tables via ORM.
#       Each attribute represents a table column.
#
# COLLEGE REQUIREMENT:
#       We do NOT use Django's built-in auth User model.
#       Instead, this is our own minimal table strictly containing:
#       - id            : Auto-increment primary key
#       - username      : Unique admin username
#       - salt          : 64-character hexadecimal random salt
#       - password_hash : 64-character output from our custom password algorithm

from django.db import models


class Admin(models.Model):
    

    username = models.CharField(
        max_length=100,
        unique=True,
        help_text="Unique admin username"
    )

    salt = models.CharField(
        max_length=64,
        help_text="64-character random hexadecimal salt generated using secrets.token_hex(32)"
    )

    password_hash = models.CharField(
        max_length=64,
        help_text="64-character hash generated by our custom teaching algorithm"
    )

    def __str__(self):
        return f"Admin({self.username})"
